2025-03-28 13:25:48,101 - root - INFO - 神奇九转策略启动
2025-03-28 13:25:48,361 - tiger_openapi - INFO - sdk version: 3.3.3
2025-03-28 13:25:48,636 - tiger_openapi - INFO - Backing off do_post(...) for 1.0s (tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='})
2025-03-28 13:25:49,697 - tiger_openapi - INFO - Backing off do_post(...) for 1.0s (tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='})
2025-03-28 13:25:50,748 - tiger_openapi - INFO - Backing off do_post(...) for 2.0s (tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='})
2025-03-28 13:25:52,799 - tiger_openapi - INFO - Backing off do_post(...) for 3.0s (tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='})
2025-03-28 13:25:55,852 - tiger_openapi - ERROR - Giving up do_post(...) after 5 tries (tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='})
2025-03-28 13:25:55,853 - tiger_openapi - ERROR - give up after 5 retries
2025-03-28 13:25:55,853 - tiger_openapi - ERROR - [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='}
Traceback (most recent call last):
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\quote\quote_client.py", line 114, in __fetch_data
    response = super(QuoteClient, self).execute(request, url=self._url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\tiger_open_client.py", line 186, in execute
    response = retry_deco(do_post)(url, query_string, self.__headers, params, self.__config.timeout,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\common\util\web_utils.py", line 17, in do_post
    return do_request('POST', url=url, query_string=query_string, headers=headers, params=params, timeout=timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\miniconda3\Lib\site-packages\tigeropen\common\util\web_utils.py", line 36, in do_request
    raise ResponseException('[' + THREAD_LOCAL.uuid + ']invalid http status ' + str(response.status) +
tigeropen.common.exceptions.ResponseException: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='}
2025-03-28 13:25:55,857 - src.data_fetcher - ERROR - 初始化老虎证券API客户端失败: [1b3ee714-0b95-11f0-80b3-84144db87756]invalid http status 502 headers: {'Content-type': 'application/json;charset=UTF-8', 'Cache-Control': 'no-cache', 'Connection': 'Keep-Alive', 'User-Agent': 'openapi-python-sdk-3.3.3'} detail body:b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' params: {'method': 'grab_quote_permission', 'version': '2.0', 'timestamp': '2025-03-28 13:25:48', 'tiger_id': '20154788', 'charset': 'UTF-8', 'sign_type': 'RSA', 'device_id': '50:eb:f6:55:fc:9d', 'sign': 'QLDKitW8CbCSmg+LxXRsHdT9kchzXtiqmgjbTXrXs8tEOWVkoCJ5dLMrB4kddAdfIpqeNEa+TiEcRpuXczeGD6oUCgHXbGZTlkXNyN+b1ZoT3A4NyraaGhzQta4fo1bLtWIexM8KACsKpCAkhWvLg1xAscaYjq6sfdNTcHFsodk='}
2025-03-28 13:25:55,857 - src.data_fetcher - WARNING - API客户端未初始化，使用测试数据
2025-03-28 13:25:55,858 - src.data_fetcher - WARNING - 生成 QQQ 的测试数据
2025-03-28 13:25:55,940 - src.data_fetcher - INFO - 测试数据已生成并缓存到: data/cache/QQQ_1m_2025-02-26_2025-03-28_mock.csv
2025-03-28 13:25:56,046 - root - INFO - 添加数据源: QQQ, 文件: data/cache/QQQ_1m_bt.csv
2025-03-28 13:25:56,047 - src.data_fetcher - WARNING - API客户端未初始化，使用测试数据
2025-03-28 13:25:56,047 - src.data_fetcher - WARNING - 生成 SPY 的测试数据
2025-03-28 13:25:56,108 - src.data_fetcher - INFO - 测试数据已生成并缓存到: data/cache/SPY_1m_2025-02-26_2025-03-28_mock.csv
2025-03-28 13:25:56,228 - root - INFO - 添加数据源: SPY, 文件: data/cache/SPY_1m_bt.csv
2025-03-28 13:25:56,229 - root - INFO - 初始资金: 100000.00
2025-03-28 13:25:56,731 - src.magic_nine_strategy - INFO - 策略初始化完成
2025-03-28 13:25:57,207 - root - ERROR - 回测过程中发生错误: 'Lines_LineSeries_LineIterator_DataAccessor_IndicatorBase_Indicator__StochasticBase_StochasticFast' object has no attribute 'fastk'
